Dr_R/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("astros.urls")),
    path("phobos/", include("phobos.urls")),
    path("deimos/", include("deimos.urls")),
]


# TODO: Check this out during deployment. I believe should be different config

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

astros/urls.py
from django.urls import path
from . import views

app_name = 'astros'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('register', views.register, name='register'),
    path('authentification/generate_code', views.generate_auth_code, name='generate_auth_code'),
    path('authentification/validate_code', views.validate_auth_code, name='validate_auth_code'),
    path('all_courses', views.all_courses, name="all_courses"),
    path('course_info/<int:course_id>', views.course_info, name="course_info"),
    path('course_info/course_enroll/<int:course_id>/<int:code>', views.course_enroll, name='course_enroll'),
    path('ece', views.state_to_truth_input, name='ece')
]

deimos/urls.py
from django.urls import path
from . import views

app_name = 'deimos'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
     path('forgot_password', views.forgot_password, name='forgot_password'),
     path('courses/notes/<int:course_id>', views.note_management, name='note_management'),
     path('courses/<int:student_id>/gradebook/<int:assignment_id>/assignment_grades', views.assignment_gradebook_student, name='assignment_gradebook_student'),
    path('courses/<int:course_id>', views.course_management, name='course_management'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>', \
         views.assignment_management, name='assignment_management'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>',\
         views.answer_question, name='answer_question'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/<int:student_id>/<int:upload_note_img>',\
         views.answer_question, name='answer_question'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:landed_question_id>/validate_answer/<int:question_id>',\
         views.validate_answer, name='validate_answer'),
     path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:landed_question_id>/<int:student_id>/<int:upload_note_img>/validate_answer/<int:question_id>',\
         views.validate_answer, name='validate_answer'),
     path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/generate_note_qr',\
         views.generate_note_qr, name='generate_note_qr'),
     path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/<int:student_id>/<int:upload_note_img>/generate_note_qr',\
         views.generate_note_qr, name='generate_note_qr'),
    path('question_nav', views.question_nav, name='question_nav'),
    path('action_menu', views.action_menu, name='action_menu'),
    path('search_question/', views.search_question, name='search_question'),
    path('compare_expressions', views.expression_compare_test, name='compare_expressions'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/save_note',\
         views.save_note, name='save_note'), 
   path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/<int:student_id>/<int:upload_note_img>/save_note',\
         views.save_note, name='save_note'), 
    path('courses/generate_practice_test/<int:practice_course_id>', views.generate_practice_test, name='generate_practice_test'),
    path('courses/practice_test_settings/<int:course_id>/<int:practice_course_id>', views.practice_test_settings, name='practice_test_settings'),
    path('courses/practice_test_settings/<int:course_id>/<int:practice_course_id>/<str:error_message>', views.practice_test_settings, name='practice_test_settings'),    
    path('courses/practice_test_page/<int:course_id>', views.practice_test_page, name='practice_test_page'), 
    path('courses/<int:course_id>/gradebook', views.gradebook, name='gradebook')    
]

phobos/urls.py
from django.urls import path
from . import views

app_name = 'phobos'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
     #
     path('forgot_password', views.forgot_password, name='forgot_password'),
     #
    path('create_course', views.create_course, name='create_course'),
    path('create_question/<int:assignment_id>', views.create_question, name='create_question'),
    path('create_question/<int:assignment_id>/<str:question_nums_types>',views.create_question,
         name='create_question'
    ),
    path('edit_question/<int:question_id>',views.edit_question,
         name='edit_question'
    ),
    path('edit_question/<int:question_id>/<str:question_nums_types>',views.edit_question,
         name='edit_question'
    ),
    path('delete_question/<int:question_id>', views.delete_question, name='delete_question'),
    path('question_bank', views.question_bank, name='question_bank'),
    path('courses/<int:course_id>', views.course_management, name='course_management'),
    path('courses/<int:course_id>/create_assignment',\
         views.create_assignment, name='create_assignment'),
    path('courses/create_assignment',\
    views.create_assignment, name='create_assignment'),
    path('delete_assignment/<int:assignment_id>', views.delete_assignment , name='delete_assignment'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>', \
         views.assignment_management, name='assignment_management'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/assign', \
         views.assign_assignment, name='assign_assignment'),    
    path('create_question/get_subtopics/<str:selected_topic>', views.get_subtopics, name='get_subtopics'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/<int:question_id>',
         views.question_view, name='question_view'),
       
     path('courses/<int:course_id>/assignments/<int:assignment_id>/<int:question_id>/export_question_to/<int:exp_assignment_id>',
          views.export_question_to, name='export_question'),

     path('calci', views.calci, name='calci'),
     path('courses/<int:course_id>/gradebook', views.gradebook, name='gradebook'),
     path('courses/<int:course_id>/<int:student_id>/student_profile', views.student_profile, name='student_profile'),
     path('courses/<int:course_id>/<int:student_id>/student_profile/modify_question_student_score/<str:new_score>/<str:question_student_id>', \
          views.modify_question_student_score, name='modify_question_score'),
     path('courses/<int:course_id>/<int:student_id>/get_questions/<int:assignment_id>',
          views.get_questions,name='get_questions'),
     path('search_question/', views.search_question, name='search_question'),
     path('sidebar/', views.sidebar, name='sidebar'),

     path('courses/<int:course_id>/enrollment_code/<str:expiring_date>',views.enrollmentCode, name = 'enrollment_code'),
     path('courses/<int:course_id>/display_enrollment_codes',views.display_codes, name='display_codes'),
     path('courses/<int:course_id>/manage_enrollment_codes', views.manage_enrollment_codes, name='manage_enrollment_codes'),
     path('courses/<int:course_id>/manage_course_info', views.manage_course_info, name='manage_course_info'),
     path('courses/<int:course_id>/save_course_info', views.save_course_info, name='save_course_info'),

     path('courses/<int:course_id>/assignments/<int:assignment_id>/<str:new_date>/edit_assignment_due_date', \
         views.edit_assignment_due_date, name='assignment_due_date'),
     path('courses/<int:course_id>/student_profile/<int:assignment_id>/edit_student_assignment_due_date', \
         views.edit_student_assignment_due_date, name='assignmentstudent_due_date'),
     path('courses/<int:course_id>/<int:student_id>/student_profile/<int:assignment_id>/edit_student_assignment_due_date', \
         views.edit_student_assignment_due_date, name='assignmentstudent_due_date'),   
     path('courses/edit_course_cover', views.edit_course_cover, name='edit_course_cover'),
     path('courses/<int:course_id>/edit_course_cover_page', views.edit_course_cover_page, name='edit_course_cover_page'),

     path('courses/<int:course_id>/assignments/<int:assignment_id>/edit_grading_scheme', \
         views.edit_grading_scheme, name='edit_grading_scheme'),

    
]

astros/models.py
from django.db import models

# Create your models here.

astros/templates/astros/all_courses.html
<!-- astros: all_courses.html-->
{% extends 'astros/layout.html' %}
{% load static %}
{% block body%}
<div class="sidebar" style="display:none">
    <header class="sidebar-header">X</header>
    <ul>
        {% if is_professor %}
            <li><a href="{% url 'phobos:index' %}">Home</a></li>
            <li><a href="{% url 'phobos:search_question' %}">Search</a></li>
        {% elif is_student %}
            <li><a href="{% url 'deimos:index' %}">Home</a></li>
            <li><a href="{% url 'deimos:search_question' %}">Search</a></li>
        {% endif %}
    </ul>
</div>
    <div id="sf-container">
        <input  id="search-field" type="text" name="search" class="page-search" data-name="course-name" placeholder="search course"/>
    </div>
    <br/>
    <h4>All courses</h4>
    <!-- Display courses -->
    <ul class="courses course-list">
        {% if is_professor%}
            {% for course, is_course_prof in courses__is_professor %}
            {% if course.name == "Practice_Test_Course" %}
            {% else %}
            {% include 'astros/prof_course_display.html' with course=course is_course_prof=is_course_prof%}
            {% endif %}
            {% endfor %}

        {% elif is_student %}
            {% for course, is_course_stud in courses__is_student %}
            {% if course.name == "Practice_Test_Course" %}
            {% else %}
                {% include 'astros/stud_course_display.html' with course=course is_course_stud=is_course_stud %}
            {% endif %}
            {% endfor %}
        
        {% else %}
            {% for course in courses %}
            {% if course.name == "Practice_Test_Course" %}
            {% else %}
                {% include 'astros/lambda_course_display.html' with course=course%}
            {% endif %}
            {% endfor %}
        {% endif %}
    </ul>

{% endblock %}
{% block scripts %}
<script src="{% static 'astros/js/course_enroll.js' %}"></script>
<script src="{% static 'deimos/js/search_generic.js' %}"></script>
{% endblock %}

astros/templates/astros/course_info.html
{% extends 'astros/layout.html' %}
{% load static %}
{% block title %} {{course.name}} {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'astros/css/course_info.css' %}"/>
{% endblock %}



{% block body %}
<div class="sidebar" style="display:none">
    <header class="sidebar-header">X</header>
    <ul>
        <li><a href="{% url 'astros:all_courses' %}">All courses</a></li>
        <li><a href="{% url 'deimos:index' %}">Home</a></li>
        <li><a href="{% url 'deimos:search_question' %}">Search</a></li>
    </ul>
</div>

<div class="course-info-container">

<div class="course-info">
    <div class="course-section">
        <div>
            <div>
                <span>
                    <h1>{{course.name}}</h1>
                </span>

                <p>
                    {{ course.description }}
                </p>

                <p style="display: none;">Created on {{ course.timestamp|date:"m/d/Y" }}</p>
            </div>
        </div>
        <div class="image-content formatted-answer-option">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="Course Image" class="c-image image-in-formatted">

            {% endif %}
        </div>
        <hr/>

        {% if is_course_stud == 1 %}
            <div>{% csrf_token %}
            <center>

                <div><a href="{% url 'deimos:course_management' course_id=course.id %}"><button class="btn edit-btn co"
                            data-course-id="{{ course.id}}">Resume Course</button></div></a>
                </center>
            </div>
        {% else %}
            <div>{% csrf_token %}
                <center>
                <div class="enrollment">
                    <button type="button" class="btn edit-btn pre-Enroll" data-course-id="{{ course.id}}">Enroll</button>
                    <input type="number" placeholder="enter the enrollment code" class="field-style" style="display:none" />
                    <button type="button" class="btn btn-success validate-btn" style="display: none;"> validate </button>
                </div>
                </center>
            </div>
        {% endif %}

    </div>

    <div class="info_body" >
        <div class="dropdown">
            <div class="head" >
                <h5>About this Course <span class="expand"></span> </h5>
            </div>
            <div class="body-text">
                <div class="formatted-answer-option">{{course_info.about_course | safe}}</div>
            </div>
        </div>
        

        <div class="dropdown">
            <div class="head">
            <h5>what you'll learn <span class="expand"></span></h5>
            </div>
            <div class="body-text">
                <div class="formatted-answer-option">{{course_info.course_skills | safe}}</div>
            </div>
        </div>

        <div class="dropdown">
            <div class="head">
                <h5>Course Plan <span class="expand"></span> </h5>
            </div>
            <div class="body-text">
                <div class="formatted-answer-option">{{course_info.course_plan | safe}}</div> 
            </div>
        </div>

        <div class="dropdown">
            <div class="head" >
                <h5>About the instructors <span class="expand"></span> </h5>
            </div>
            <div class="body-text">
            {% if course_info.instructors_image %}
                <div class="instructors-image formatted-answer-option">
                    <img scr="{{course_info.instructors_image.url}}" alt="instructors-image" class="image-in-formatted"/>
                </div>
            {% endif %}
            <div class="formatted-answer-option">{{course_info.course_instructors | safe }}</div>
            </div>
        </div>

    </div>


</div>
    
</div>

<script src="{% static 'astros/js/course_enroll.js' %}"></script>
<script src="{% static 'astros/js/course_info.js' %}"></script>

{% endblock %}

astros/templates/astros/index.html
<!--astros:index.html-->
{% extends "astros/registration_layout.html" %}
{% load static %}

    {% block body %}
        
        
    <div class="landing-container">
        <div class="landing-leftside">
            <img id="mars-image" src="{% static 'astros/images/mars.jpg' %}" alt="Mars image"/>
        </div>

        <div class="lading-rightside">
            <nav class="navbar">
                <a href="{% url 'astros:register' %}" id="r-btn"><button class="btn btn-primary" > Register </button></a>
            </nav>
            <div class="intro-section">
                <div class="genesis-quote">
                    In the beginning God Created heaven and <span class="canceled-text">Earth</span> 
                    <span class="mars-text"> Mars.</span>
                    <p class="reference">
                        <em>~Genesis 1:1</em>
                    </p>
                </div>
                <!--
                    <div class="welcome-message">
                    <strong><em>Welcome to Dr R!</em></strong><br/> Student or Instructor? Login to create/continue courses.
                    You don't have an account with us? Register in 2 mins 37 seconds.
                    <p><a href=""><button class="login-button btn btn-primary"> Login </button></a></p>
                </div>
                -->
                <div class="welcome-section">
                    <p><a href="{% url 'astros:login' %}"><button class="btn btn-primary" id="login-button"> Login </button></a></p>
                  </div>
                  
            </div>
        </div>
    </div>    
        
    {% endblock %}

astros/templates/astros/lambda_course_display.html
<!-- astros: lambda_course_display.html -->
<li class="course-li" data-course-id="{{ course.id }}">
    <div class="course-section">
        <div class="image-container">
            {% if course.image %}
                <img src="{{ course.image.url }}" alt="Course Image" class="course-image">
            {% endif %}
        </div>
        <div class="c-text">
            <span class="c-name"><strong>{{course.name}}</strong></span>
            <p class="c-description">{% if course.description|length > 90 %}
                {{ course.description|slice:":90" }}...
            {% else %}
                {{ course.description }}
            {% endif %}</p>
        
            <p class="timestamp" style="display: none;">Created on {{ course.timestamp|date:"m/d/Y" }}</p>
        </div>
    </div>


</li>

astros/templates/astros/layout.html
<!-- astros: layout.html-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} Astros {% endblock %}</title>
        {% block style %}
        {% endblock %}
        <link rel="stylesheet" href="{% static 'astros/css/style.css' %}"/> 
        {% block bootstrap %}<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"> {% endblock %}
        <link rel="icon" href="{% static 'astros/images/mars.ico' %}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <div id="preloader"></div>
    <body class="body">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item" style="display:none">
                    <strong>@{{ user.username }}</strong>
                </li>
                <li class="nav-item logout-link">
                    <!--LOGOUT link doesn't matter. It can be phobos or deimos and will do the same thing-->
                    <a id="logout-link" class="nav-link" href="{% url 'phobos:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item logout-link">
                    <!--LOGOUT link doesn't matter. It can be phobos or deimos and will do the same thing-->
                    <a id="logout-link" class="nav-link" href="{% url 'astros:login' %}">Login</a>
                </li>                
            {% endif %}
        </ul>
        
    <!--Top of the page. -->
    <div class="glass-container">
        <div class="top-page-image">
        </div>
    </div>
    <div id="brand-section">
        <div id="orange-line"></div>
        <div id="brand-version-text">
            <div id="bvt1">Dr. r</div>
            <div id="bvt2">phobos</div>
        </div>

        <div id="double-orange-lines">
            <div class="dol"></div>
            <div class="dol"></div>
        </div>
        <div class="message">
            <span id="m1">And Man created AI</span> <br/> 
            <span id="m2">in his image.</span>  
        </div>
    </div>
    
    <!-- Creation/management menu -->
    <div id="options">
        <div id="triple-orange-lines">
            <div class="tol"></div>
            <div class="tol"></div>
            <div class="tol"></div>
        </div>
    </div>
        {% block body %} {% endblock %}
        <script src="{% static 'phobos/js/sidebar.js' %}"></script>
        {% block scripts %}{% endblock %}
    </body>
    
    <script>
        var loader = document.querySelector('#preloader');
        window.addEventListener('load', ()=>{
            loader.classList.add('hide');
        });
    </script>
</html>

astros/templates/astros/login.html
<!--astros:login.html-->
{% extends 'astros/registration_layout.html' %}

{% load static %}

{% block title %} Login {% endblock %}

{% block body%}
<div id="registration-container" class="bs-overrides">
    
    <br/><br/>
    <div class="register-deimos registration-form main-form">
        <p>Login as a <strong><em>student</em></strong> on the <strong><em>Deimos</em></strong> version</p>

        {% if message_deimos %}
        <div>{{ message_deimos }}</div>
        {% endif %}

        <form action="{% url 'deimos:login' %}" method="post" class="original-form">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="btn btn-primary r" type="submit" value="Login">
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        </form>
        <ul class='forgot-password-link'>forgot password?</ul>
    <br>
    <br>
            <div class="change-pwd-deimos registration-form cpwd"  style="display: none">
                <form action="{% url 'deimos:forgot_password' %}" method="post" class="change-pwd-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="email" name="email" placeholder="Email Address">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password" placeholder="New Password">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
                    </div>
                    <div class="form-group authentication-area closed" style="display: none">
                        <input class="form-control input-code" type="number" name="validation_code" placeholder="Enter code">
                    </div>
                    <div class="forgot-password-div">
                        <button class="btn btn-primary submit-btn-register" type="button">Submit</button>
                        <button class="btn btn-danger cancel-btn" type="button">Cancel</button>
                    </div>
                    
                </form>
            </div>
    </div>

    <br/><div class="vertical-line"></div><br/>
    <div class="register-phobos registration-form main-form">
        <p>Login as an <strong><em>instructor</em></strong> on the <strong><em>Phobos</em></strong> version</p>

        {% if message_phobos %}
        <div>{{ message_phobos }}</div>
        {% endif %}
        <form action="{% url 'phobos:login' %}" method="post" class="original-form">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="btn btn-primary r" type="submit" value="Login">
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        </form>
        <ul class='forgot-password-link'>forgot password?</ul>
        <br>
        <br>

        <div class="change-pwd-phobos registration-form cpwd"  style="display: none">
            <form action="{% url 'phobos:forgot_password' %}" method="post" class="change-pwd-form">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="email" name="email" placeholder="Email Address">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="New Password">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
                </div>
                <div class="form-group authentication-area closed" style="display: none">
                    <input class="form-control input-code" type="number" name="validation_code" placeholder="Enter code">
                </div>
                <div class="forgot-password-div">
                    <button class="btn btn-primary r submit-btn-register" type="button">Submit</button>
                    <button class="btn btn-danger r cancel-btn" type="button">Cancel</button>
                </div>
                
            </form>
        </div>
    </div>

</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'astros/js/registration.js' %}"></script>
{% endblock %}

astros/templates/astros/prof_course_display.html
<!-- astros: prof_course_display.html -->
<li class="course-li" data-course-id="{{ course.id }}">
    <div class="course-section">
        <div class="image-container">
            {% if course.image %}
                <img src="{{ course.image.url }}" alt="Course Image" class="course-image">
            {% endif %}
        </div>
        <div class="c-text">
            <span class="c-name course-name"><strong>{{course.name}}</strong></span>
            <p class="c-description">
                {{ course.description }}</p>
            <p class="timestamp" style="display: none;">Created on {{ course.timestamp|date:"m/d/Y" }}</p>
        </div>
    </div>
    {% if is_course_prof == 1 %}
        <div class="edit-section il">{% csrf_token %}
            <div><a href="{% url 'phobos:course_management' course_id=course.id %}"><button class="btn edit-btn co" data-course-id="{{ course.id}}">Manage</button></div></a>
        
        </div>
    {% endif %}

</li>

astros/templates/astros/register.html
<!--astros:register.html-->
{% extends 'astros/registration_layout.html' %}

{% load static %}

{% block title %} Register {% endblock %}

{% block body%}
    <div id="registration-container" class="bs-overrides">
        <br/><br/> 
    <div class="register-deimos registration-form">
        <p>Register as a <strong><em>student</em></strong> on the <strong><em>Deimos</em></strong> version</p>
        {% if message_deimos %}
            <div>{{ message_deimos }}</div>
        {% endif %}
        <form action="{% url 'deimos:register' %}" method="post" class="deimos register" >
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="first_name" placeholder="First name">
            </div>
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="last_name" placeholder="Last name">
            </div>
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <div class="form-group authentication-area closed" style="display: none">
                <input class="form-control input-code" type="number" name="validation_code" placeholder="Enter code">
            </div>
            <button class="btn btn-primary r submit-btn-register" type="button"> Register </button>
        </form>
    </div>

    <br/><div class="vertical-line"></div><br/>

    <div class="register-phobos registration-form">
        <p>Register as an <strong><em>instructor</em></strong> on the <strong><em>Phobos</em></strong> version</p>
        {% if message_phobos %}
            <div>{{ message_phobos }}</div>
        {% endif %}
        <form action="{% url 'phobos:register' %}" method="post" class="phobos register">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="first_name" placeholder="First name">
            </div>
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="last_name" placeholder="Last name">
            </div>
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="department" placeholder="Department">
            </div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <div class="form-group authentication-area closed" style="display: none">
                <input class="form-control input-code" type="number" name="validation_code" placeholder="Enter code">
            </div>
            <button class="btn btn-primary r submit-btn-register" type="button"> Register </button>
        </form>
    </div>
</div>

{% endblock %}
{% block scripts %}
<script src="{% static 'astros/js/registration.js' %}"></script>
{% endblock %}

astros/templates/astros/stud_course_display.html
<!-- astros: stud_course_display.html -->
<li class="course-li" data-course-id="{{ course.id }}">
    <div class="course-section">
        <div class="image-container">
            {% if course.image %}
                <img src="{{ course.image.url }}" alt="Course Image" class="course-image">
            {% endif %}
        </div>
        <div class="c-text">
            <span class="c-name course-name"><strong>{{course.name}}</strong></span>
            <p class="c-description">{% if course.description|length > 90 %}
                {{ course.description|slice:":90" }}...
            {% else %}
                {{ course.description }}
            {% endif %}</p>
        
            <p class="timestamp" style="display: none;">Created on {{ course.timestamp|date:"m/d/Y" }}</p>
        </div>
    </div>

        <div class="edit-section il">{% csrf_token %}
            <div><a href="{% url 'astros:course_info' course_id=course.id %}"><button class="btn edit-btn co" data-course-id="{{ course.id}}">View Course</button></div></a>
        
        </div>

</li>