Dr_R/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("astros.urls")),
    path("phobos/", include("phobos.urls")),
    path("deimos/", include("deimos.urls")),
]


# TODO: Check this out during deployment. I believe should be different config

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

astros/urls.py
from django.urls import path
from . import views

app_name = 'astros'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('register', views.register, name='register'),
    path('authentification/generate_code', views.generate_auth_code, name='generate_auth_code'),
    path('authentification/validate_code', views.validate_auth_code, name='validate_auth_code'),
    path('all_courses', views.all_courses, name="all_courses"),
    path('course_info/<int:course_id>', views.course_info, name="course_info"),
    path('course_info/course_enroll/<int:course_id>/<int:code>', views.course_enroll, name='course_enroll'),
    path('ece', views.state_to_truth_input, name='ece')
]

deimos/urls.py
from django.urls import path
from . import views

app_name = 'deimos'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
     path('forgot_password', views.forgot_password, name='forgot_password'),
     path('courses/notes/<int:course_id>', views.note_management, name='note_management'),
     path('courses/<int:student_id>/gradebook/<int:assignment_id>/assignment_grades', views.assignment_gradebook_student, name='assignment_gradebook_student'),
    path('courses/<int:course_id>', views.course_management, name='course_management'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>', \
         views.assignment_management, name='assignment_management'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>',\
         views.answer_question, name='answer_question'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/<int:student_id>/<int:upload_note_img>',\
         views.answer_question, name='answer_question'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:landed_question_id>/validate_answer/<int:question_id>',\
         views.validate_answer, name='validate_answer'),
     path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:landed_question_id>/<int:student_id>/<int:upload_note_img>/validate_answer/<int:question_id>',\
         views.validate_answer, name='validate_answer'),
     path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/generate_note_qr',\
         views.generate_note_qr, name='generate_note_qr'),
     path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/<int:student_id>/<int:upload_note_img>/generate_note_qr',\
         views.generate_note_qr, name='generate_note_qr'),
    path('question_nav', views.question_nav, name='question_nav'),
    path('action_menu', views.action_menu, name='action_menu'),
    path('search_question/', views.search_question, name='search_question'),
    path('compare_expressions', views.expression_compare_test, name='compare_expressions'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/save_note',\
         views.save_note, name='save_note'), 
   path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/<int:student_id>/<int:upload_note_img>/save_note',\
         views.save_note, name='save_note'), 
    path('courses/generate_practice_test/<int:practice_course_id>', views.generate_practice_test, name='generate_practice_test'),
    path('courses/practice_test_settings/<int:course_id>/<int:practice_course_id>', views.practice_test_settings, name='practice_test_settings'),
    path('courses/practice_test_settings/<int:course_id>/<int:practice_course_id>/<str:error_message>', views.practice_test_settings, name='practice_test_settings'),    
    path('courses/practice_test_page/<int:course_id>', views.practice_test_page, name='practice_test_page'), 
    path('courses/<int:course_id>/gradebook', views.gradebook, name='gradebook')    
]

phobos/urls.py
from django.urls import path
from . import views

app_name = 'phobos'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
     #
     path('forgot_password', views.forgot_password, name='forgot_password'),
     #
    path('create_course', views.create_course, name='create_course'),
    path('create_question/<int:assignment_id>', views.create_question, name='create_question'),
    path('create_question/<int:assignment_id>/<str:question_nums_types>',views.create_question,
         name='create_question'
    ),
    path('edit_question/<int:question_id>',views.edit_question,
         name='edit_question'
    ),
    path('edit_question/<int:question_id>/<str:question_nums_types>',views.edit_question,
         name='edit_question'
    ),
    path('delete_question/<int:question_id>', views.delete_question, name='delete_question'),
    path('question_bank', views.question_bank, name='question_bank'),
    path('courses/<int:course_id>', views.course_management, name='course_management'),
    path('courses/<int:course_id>/create_assignment',\
         views.create_assignment, name='create_assignment'),
    path('courses/create_assignment',\
    views.create_assignment, name='create_assignment'),
    path('delete_assignment/<int:assignment_id>', views.delete_assignment , name='delete_assignment'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>', \
         views.assignment_management, name='assignment_management'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/assign', \
         views.assign_assignment, name='assign_assignment'),    
    path('create_question/get_subtopics/<str:selected_topic>', views.get_subtopics, name='get_subtopics'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/<int:question_id>',
         views.question_view, name='question_view'),
       
     path('courses/<int:course_id>/assignments/<int:assignment_id>/<int:question_id>/export_question_to/<int:exp_assignment_id>',
          views.export_question_to, name='export_question'),

     path('calci', views.calci, name='calci'),
     path('courses/<int:course_id>/gradebook', views.gradebook, name='gradebook'),
     path('courses/<int:course_id>/<int:student_id>/student_profile', views.student_profile, name='student_profile'),
     path('courses/<int:course_id>/<int:student_id>/student_profile/modify_question_student_score/<str:new_score>/<str:question_student_id>', \
          views.modify_question_student_score, name='modify_question_score'),
     path('courses/<int:course_id>/<int:student_id>/get_questions/<int:assignment_id>',
          views.get_questions,name='get_questions'),
     path('search_question/', views.search_question, name='search_question'),
     path('sidebar/', views.sidebar, name='sidebar'),

     path('courses/<int:course_id>/enrollment_code/<str:expiring_date>',views.enrollmentCode, name = 'enrollment_code'),
     path('courses/<int:course_id>/display_enrollment_codes',views.display_codes, name='display_codes'),
     path('courses/<int:course_id>/manage_enrollment_codes', views.manage_enrollment_codes, name='manage_enrollment_codes'),
     path('courses/<int:course_id>/manage_course_info', views.manage_course_info, name='manage_course_info'),
     path('courses/<int:course_id>/save_course_info', views.save_course_info, name='save_course_info'),

     path('courses/<int:course_id>/assignments/<int:assignment_id>/<str:new_date>/edit_assignment_due_date', \
         views.edit_assignment_due_date, name='assignment_due_date'),
     path('courses/<int:course_id>/student_profile/<int:assignment_id>/edit_student_assignment_due_date', \
         views.edit_student_assignment_due_date, name='assignmentstudent_due_date'),
     path('courses/<int:course_id>/<int:student_id>/student_profile/<int:assignment_id>/edit_student_assignment_due_date', \
         views.edit_student_assignment_due_date, name='assignmentstudent_due_date'),   
     path('courses/edit_course_cover', views.edit_course_cover, name='edit_course_cover'),
     path('courses/<int:course_id>/edit_course_cover_page', views.edit_course_cover_page, name='edit_course_cover_page'),

     path('courses/<int:course_id>/assignments/<int:assignment_id>/edit_grading_scheme', \
         views.edit_grading_scheme, name='edit_grading_scheme'),

    
]

phobos/forms.py
# forms.py

from django import forms
from .models import Course, Assignment, Question

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        # TODO: Implement image upload. Make sure the image is uploaded to media/phobos/images/course_images
        fields = ['image', 'name', 'subject', 'difficulty_level','description','topics','professors']
        widgets = {
            'image': forms.FileInput(attrs={'id': 'course-image'}),  # Add this line
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'course-name'}),
            'subject': forms.Select(attrs={'class': 'form-control', 'id': 'course-subject'}),
            # 'number_of_students': forms.NumberInput(attrs={'class': 'form-control', 'id': 'students-count'}),
            'difficulty_level': forms.Select(attrs={'class': 'form-control', 'id': 'difficulty-level'}),
            # TODO: the oninput is to a function to be defined in the JS file
            'description': forms.Textarea(attrs={'class': 'form-control', 'id': 'course-description',\
                                                  'style':"height: 30px" ,\
                                                    'oninput':"resizeTextarea(this)"}),
            'topics': forms.SelectMultiple(attrs={'class': 'form-control', 'id':'course-topics'}),
            'professors': forms.SelectMultiple(attrs={'class': 'form-control', 'id': 'course-professors'}),
        }

class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ['name', 'difficulty_level', 'due_date']  # Removed 'course' from fields
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'assignment-name'}),
            'difficulty_level': forms.Select(attrs={'class': 'form-control', 'id': 'difficulty-level'}),
            # 'due_date': forms.DateInput(attrs={'class': 'form-control datepicker', 'id': 'assignment-due-date'}),
        }

    def __init__(self, *args, **kwargs):
        course = kwargs.pop('course', None)  # Pop the 'course' argument if it was passed
        super().__init__(*args, **kwargs)
        initial_course_value = course if course else ''
        self.fields['course'] = forms.CharField(
            initial=initial_course_value,
            label='Course',
            widget=forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            required=False
        )

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text', 'topic', 'sub_topic']

phobos/templates/phobos/assignment_management.html
<!-- phobos: assignment_management.html-->
{% extends 'phobos/layout.html' %}
{% block title %} Assignment {% endblock %}
{% load static %}
{% load my_custom_tags %}
{% block body%}
<div class="sidebar" style="display:none">
    <header class="sidebar-header">X</header>
    <ul>
        <li><a href="{% url 'phobos:index' %}">Home</a></li>
        <li><a href="{% url 'phobos:create_question' assignment_id=assignment.id %}">Create Question</a></li>
        {% if not is_question_bank %}
            <li><a href="{% url 'phobos:course_management' course_id=assignment.course.id %}">Assigments</a></li>
        {% endif %}
        <li><a href="{% url 'phobos:question_bank' %}">Question Bank</a></li>
        <li><a href="{% url 'astros:all_courses' %}">All Courses</a></li>
        <li><a href="{% url 'phobos:delete_assignment' assignment_id=assignment.id %}">Delete</a></li>
    </ul>
</div>

<nav class="navbar-custom" >
    <a class="nav-link home-btn" href="{% url 'phobos:course_management' course_id=course.id %}">Assignments</a>
    <a class="nav-link view-notes-btn" href="{% url 'phobos:create_question' assignment_id=assignment.id %}">Create Question</a>
    <a class="nav-link gradebook-btn" href="{% url 'phobos:gradebook' course_id=course.id %}">GradeBook</a>
  </nav>

  <div class="side-info-icon" title="Info">
    <a href="{% url 'phobos:edit_grading_scheme' course_id=course.id assignment_id=assignment.id %}"><ion-icon name="settings"></ion-icon></a>
  </div>
    <div class="sf-container">
        <input type="text" name="search_question" class="page-search search-field w-limit-50" data-name="question-name" placeholder="search question"/>
    </div>
    <br/>
    <br/>
    <h4 class="suggestion original-size page-title">{{assignment.course.name}}: {{assignment.name}}</h4>
    <hr/>
    <div class="assignment-options page-title">
    {% if not assignment.is_assigned %}
        <button class="btn btn-outline-success assign-btn" data-assignment-id="{{assignment.id}}">Assign</button>
    {% endif %}
<!-- Due Date functionalities-->
    <button class="btn btn-outline-info due_date-btn"  data-assignment-id="{{assignment.id}}">Change Due Date</button>
        <div  class="due-date-div" style="display: none" >
            <input type="datetime-local"  class="input-new-due-date-field">
            <input type="button" class="save-new-due-date-field btn btn-outline-info" value="OK">
        </div>
    </div>
   
    <ul class="courses course-list">
        {% for question in questions %}
            {% include 'phobos/question_display.html' with question=question assignment_id=assignment.id course_id=assignment.course.id%}
        {% endfor %}
    </ul>

{% endblock %}
{% block scripts%}
<script src="{% static 'phobos/js/search_generic.js' %}"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<script src="{% static 'deimos/js/assignment_management.js' %}"></script>
{% if not assignment.is_assigned %}
<script src="{% static 'phobos/js/assign_question.js' %}"></script>
{% endif %}
<script src="{% static 'phobos/js/extend_due_date.js' %}"></script>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
{% endblock %}

phobos/templates/phobos/course_display.html
<!-- phobos: course_display.html -->
<li class="course-li" data-course-id="{{ course.id }}">
    <a href="{% url 'phobos:course_management' course_id=course.id %}">
        <div class="course-section">
            <div class="image-container">
                {% if course.image %}
                    <img src="{{ course.image.url }}" alt="Course Image" class="course-image">
                {% endif %}
            </div>
            <div class="c-text">
                <span class="c-name course-name"><strong>{{course.name}}</strong></span>
                <p class="c-description">
                    {{ course.description }}</p>
                <p class="timestamp" style="display: none;">Created on {{ course.timestamp|date:"m/d/Y" }}</p>
            </div>
        </div>
      </a>
      <div class="dropdown"  style="position: absolute; top: 0%; right: 1%; z-index:2;">
        <ion-icon name="options-outline" class="btn btn-secondary dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown"></ion-icon>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{%url 'phobos:edit_course_cover_page' course_id=course.id %}">Edit</a><br>
            <!--<a class="dropdown-item" href="#">delete</a><br>
            <a class="dropdown-item" href="#">Something else here</a><br>-->
        </div>
      </div>
</li>

phobos/templates/phobos/course_management.html
<!-- phobos: course_management.html-->
{% extends 'phobos/layout.html' %}
{% block title %} Course {% endblock %}
{% load static %}
{% block body%}
    <div class="sidebar" style="display:none">
        <header class="sidebar-header">X</header>
        <ul>
            <li><a href="{% url 'phobos:index' %}">Home</a></li>
            {% if not is_question_bank %}
                <li><a href="{% url 'phobos:manage_course_info' course_id=course.id %}">Course Info</a></li> 
                <li><a href="{% url 'phobos:gradebook' course_id=course.id %}">Gradebook</a></li>
                <li><a href="{% url 'phobos:manage_enrollment_codes' course_id=course.id %}">Enrollments</a></li>
                <li><a href="{% url 'phobos:question_bank' %}">Question Bank</a></li>
            {% endif %}
            <li><a href="{% url 'phobos:search_question' %}">Search</a></li>
            
        </ul>
    </div>

    
<nav class="navbar-custom">
    <a class="nav-link home-btn" href="{% url 'phobos:index' %}">Home </a>
    {% if not is_question_bank %}
        <a class="nav-link view-notes-btn" href="{% url 'phobos:create_assignment' course_id=course.id %}">Create Assignment</a>
        <a class="nav-link gradebook-btn" href="{% url 'phobos:gradebook' course_id=course.id %}">GradeBook</a>
        <a class="nav-link" href="{% url 'phobos:manage_course_info' course_id=course.id %}">Course Info</a>
    {% endif %}
</nav>

<div class="sf-container">
    <input type="text" name="search" class="page-search search-field w-limit-50" data-name="assignment-name" placeholder="search assignment" />
</div>
    <br/>
    
    <h4>{{course.name}}</h4><hr/>
    <!-- Display course's assignments -->
    <ul class="courses course-list">
        {% for assignment in assignments %}
            {% include 'phobos/assignment_display.html' with assignment=assignment course=course %}
        {% endfor %}
    </ul>
{% endblock %}
{% block scripts %}
    <script src="{% static 'phobos/js/search_generic.js' %}"></script>
{% endblock %}

phobos/templates/phobos/create_question.html
<!-- phobos: create_question.html -->
{% extends 'phobos/layout.html' %}
{% load static %}
{% block title%} Create question {% endblock %}
{% block body %}

<div class="sidebar" style="display:none">
  <header class="sidebar-header">X</header>
  <ul>
      <li><a href="{% url 'phobos:index' %}">Home</a></li>
      <li><a href="{% url 'phobos:assignment_management' assignment_id=assignment.id course_id=assignment.course.id %}">Questions</a></li>
      <li><a href="{% url 'phobos:course_management' course_id=assignment.course.id %}">Assignments</a></li>
      <li><a href="{% url 'phobos:search_question' %}">Search Question</a></li>
  </ul>
</div>
    <!-- TODO: Include buttons and invent listeners to create subquestions.-->
    
    <div class="page-container" id="create-question">
    <br/>

    <form class="create-mode" method="post" enctype="multipart/form-data" id="question-form"
     action="{% url 'phobos:create_question' assignment_id=assignment.id %}">
      {% csrf_token %}
      
      <div class="question">
        <div id="topics-subtopics">
          <h3 class="original-size suggestion">Create a Question</h3>
            <div class="topics_dropdown option-section">
              <label for="topic" class="option-label">Topic: </label>
              
              <select title="select topic" name="topic" id="topicSelect" class="option-field">
                  <option value selected disabled>Choose topic</option>
                  {% for topic in topics%}
                      <option value="{{topic}}">
                        {{topic}}
                      </option>
                  {% endfor %}
              </select>
            </div>
          
            <div class="sub_topics_dropdown option-section">
              <label for="sub topic" class="option-label">Subtopic: </label>
              <select title="select subtopic" name="sub_topic" id="subTopicSelect" class="option-field">
                <option value selected disabled>Choose subtopic</option>
              </select>

            </div>
            <div class="question_difficulty option-section">
              <label for="difficulty" class="option-label">Difficulty: </label>
              <select title="Difficulty" name="question_difficulty" class="option-field">
                {% for question_difficulty in question_difficulties %}
                  <option value="{{question_difficulty}}">
                    {{question_difficulty}}
                  </option>
                {% endfor %}
              </select>
            </div>

        </div>
         <br/>
         <div class="question-content form-group">
            <br/>
            <div class="created-vars"></div>
            <br/>
          </div>
          <div id="all-question-blocks"></div>
      </div>
 

    {% include 'phobos/calci.html' %}
    <br/>
    <input type="submit" class="btn btn-success create-question-btn" value="Create Question">
    <br/>
    <div class="question-settings side">
      <div class="settings-icon side-info-icon" title="Settings">
        <ion-icon name="settings"></ion-icon>
      </div>
      <div class="hide side-info">
      <span class="side-info-x">X</span><br/>
      <h4 class="suggestion original-size">Settings</h4>
      <hr/>
      <select title="Part" name="settings-select" class="settings-select field-style">
      </select>
      <div class="settings-modification">
          <div class="settings-item"> 
            <div class="settings-label">Number of points:</div>
            <div class="settings-input-div">
              <input class="field-style settings init-num-pts" type="number" name="num_points" min="0" max="25"
              placeholder="Number of points e.g. 10" value="{{assignment.grading_scheme.num_points}}"/>
            </div>
          </div>
          <div class="settings-item">
            <div class="settings-label">Max attempts:</div>
            <div class="settings-input-div">
              <input class="field-style settings" type="number" name="max_num_attempts" min="1" 
              placeholder="Max number of attempts" value="{{assignment.grading_scheme.struct_num_attempts}}"/>
            </div>
          </div>
          <div class="settings-item">
            <div class="settings-label">% deduct per attempt:</div>
            <div class="settings-input-div">
              <input class="field-style settings" type="number" name="deduct_per_attempt" min="0" max="1"
              placeholder="% deduct per attempt" value="{{assignment.grading_scheme.deduct_per_attempt}}"/>
            </div>
          </div >
          <div class="settings-item">
            <div class="settings-label">% Margin error:</div>
            <div class="settings-input-div"> 
              <input class="field-style settings" type="number" name="margin_error" min="0" max="1"
              placeholder="% margin error" value="{{assignment.grading_scheme.margin_error}}"/>
            </div>
          </div>
          <div class="settings-item">
            <div class="settings-label">Max attempts(units):</div>
            <div class="settings-input-div">
              <input class="field-style settings" type="number" name="units_num_attempts" min="1"
              placeholder="Max attempts(units)" value="{{assignment.grading_scheme.units_num_attempts}}"/>
            </div>
          </div>
          <div class="settings-item">
            <div class="settings-label">% points for units:</div>
            <div class="settings-input-div">
              <input class="field-style settings" type="number" name="percentage_pts_units" min="0" max="1"
              placeholder="% points for units" value="{{assignment.grading_scheme.percentage_pts_units}}"/>
            </div>
          </div>
          <div class="settings-item">
            <div class="settings-label">Max attempts(mcq):</div>
            <div class="settings-input-div">
              <input class="field-style settings" type="number" name="max_mcq_num_attempts" min="1"
              placeholder="Max number of attempts(mcq)" value="{{assignment.grading_scheme.mcq_num_attempts}}"/>
            </div>
          </div>
          <div class="settings-item">
            <div class="settings-label">% deduct per attempt(mcq):</div>
            <div class="settings-input-div">
              <input class="field-style settings" type="number" name="mcq_deduct_per_attempt" min="0" max="1"
              placeholder="% deduct per attempt(mcq)" value="{{assignment.grading_scheme.mcq_deduct_per_attempt}}"/>
            </div>
          </div>
          
      </div>
      </div>
    </div>
    <div class="question-variables side">
      <div class="side-info-icon" title="Info">
        <ion-icon name="add-circle-outline"></ion-icon>
      </div>
      <div class="hide side-info">
        <span class="side-info-x">X</span><br/>
        <hr/>
        <h3 class="suggestion original-size">Variables</h3>
        
        <div class="add-var-section" title="variables">
          
          <div class="var-info-div">
              <div><input class="var-symbol field-style" type="text" placeholder="enter symbol e.g. x"/></div>
              <div><input class="var-domain field-style" type="text" placeholder="enter intervals e.g.[1,3] [-8, 20]"/></div>
              <div><input class="var-step-size field-style" type="number" min="0" placeholder ="step size (optional)" pattern="^?[0-9]*[.,]?[0-9]+" title="Please enter a valid float number."></div>
  
              <div class="type-selection">
                <label>
                    <input type="radio" class="var-type-float" name="varType" value="float" checked> Float
                </label>
                <label>
                    <input type="radio" class="var-type-int" name="varType" value="int"> Int
                </label>
              </div>
              <div><button type="button" class="btn btn-success btn-create-var">Create var</button></div>
              
          </div>
          
        </div>
        <br/>
        <div class="added-vars">

        </div>

      </div>
      
    </div>
    </form>

  </div>

{% endblock %}
{% block scripts%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjs/11.9.1/math.js"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<script src="{% static 'phobos/js/subtopics.js' %}"></script>
<script src="{% static 'phobos/js/create_question.js' %}"></script>
<script src="{% static 'phobos/js/question.js' %}"></script>
<script src="{% static 'phobos/js/calci.js' %}"></script>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
{% endblock %}

phobos/templates/phobos/index.html
<!-- phobos: index.html-->
{% extends 'phobos/layout.html' %}
{% load static %}
{% block body%}
    <div class="sidebar" style="display:none">
        <header class="sidebar-header">X</header>
        <ul>
            <li><a href="{% url 'phobos:index'%}">Home</a></li>
            <li><a href="{% url 'astros:all_courses' %}">All courses</a></li>
            <li><a href="{% url 'phobos:create_course' %}">Create Course</a></li>
            <li><a href="{% url 'deimos:compare_expressions' %}">Compare Expressions</a></li>
            <li><a href="{% url 'phobos:search_question' %}">Search</a></li>
        </ul>
    </div>
    
    <nav class="navbar-custom">
        <a class="nav-link home-btn" href="{% url 'astros:all_courses' %}">All Courses</a>
        <a class="nav-link view-notes-btn" href="{% url 'phobos:create_course' %}">Create Course</a>
      </nav>

    <div class="sf-container">
        <input type="text" name="search" class="page-search search-field w-limit-50" data-name="course-name" placeholder="search course"/>
    </div>
    <br/>

        <h4>My courses</h4>
    <!-- Display professor's courses -->
    <ul class="courses course-list">
        {% for course in courses%}
            {% include 'phobos/course_display.html' with course=course%}
        {% empty %}
            <h4 class="suggestion original-size" style="width:100%"> You did not create a course yet. Go to 
                <a href="{% url 'phobos:create_course' %}">create</a> to create a new course. 
            </h4>
        {% endfor %}
    </ul>
{% endblock %}
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<script src="{% static 'phobos/js/search_generic.js' %}"></script>
{% endblock %}

phobos/templates/phobos/search_question.html
<!-- phobos: search_questions.html-->
{% extends 'phobos/layout.html' %}
{% block title %} Search {% endblock %}
{% load static %}
{% block body%}
    <div class="sidebar" style="display:none">
        <header class="sidebar-header">X</header>
        <ul>
            <li><a href="{% url 'phobos:index'%}">Home</a></li>
        </ul>
    </div>
    <form action="{% url 'phobos:search_question' %}" method="post" class="search-form">
        {% csrf_token %} 
        <div class="sf-container">
            {% if search_text %}
                <input  class="search-field" type="text" name="search_question" placeholder="search question" value="{{search_text}}"/>
            {% else %}
                <input  class="search-field" type="text" name="search_question" placeholder="search question" />
            {% endif %}
        </div>
    </form>
    <br/>
    <br/>
    <h4>Search Results...</h4><hr/>
    
    <!-- Display assignment's questions -->
    <ul class="courses course-list">
        {% for similar_question in similar_questions %}
            {% include 'phobos/question_display.html' with question=similar_question.question assignment_id=similar_question.question.assignment.id course_id=similar_question.question.assignment.course.id%}
        {% empty %}
            <h4 class="suggestion original-size" style="width:100%;"> Enter your question in the search bar and hit enter.</h4>
        {% endfor %}
    </ul>

{% endblock %}
{% block scripts%}
<script src="{% static 'phobos/js/search_question.js' %}"></script>
{% endblock %}