Dr_R/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("astros.urls")),
    path("phobos/", include("phobos.urls")),
    path("deimos/", include("deimos.urls")),
]


# TODO: Check this out during deployment. I believe should be different config

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

astros/urls.py
from django.urls import path
from . import views

app_name = 'astros'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('register', views.register, name='register'),
    path('authentification/generate_code', views.generate_auth_code, name='generate_auth_code'),
    path('authentification/validate_code', views.validate_auth_code, name='validate_auth_code'),
    path('all_courses', views.all_courses, name="all_courses"),
    path('course_info/<int:course_id>', views.course_info, name="course_info"),
    path('course_info/course_enroll/<int:course_id>/<int:code>', views.course_enroll, name='course_enroll'),
    path('ece', views.state_to_truth_input, name='ece')
]

deimos/urls.py
from django.urls import path
from . import views

app_name = 'deimos'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
     path('forgot_password', views.forgot_password, name='forgot_password'),
     path('courses/notes/<int:course_id>', views.note_management, name='note_management'),
     path('courses/<int:student_id>/gradebook/<int:assignment_id>/assignment_grades', views.assignment_gradebook_student, name='assignment_gradebook_student'),
    path('courses/<int:course_id>', views.course_management, name='course_management'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>', \
         views.assignment_management, name='assignment_management'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>',\
         views.answer_question, name='answer_question'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/<int:student_id>/<int:upload_note_img>',\
         views.answer_question, name='answer_question'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:landed_question_id>/validate_answer/<int:question_id>',\
         views.validate_answer, name='validate_answer'),
     path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:landed_question_id>/<int:student_id>/<int:upload_note_img>/validate_answer/<int:question_id>',\
         views.validate_answer, name='validate_answer'),
     path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/generate_note_qr',\
         views.generate_note_qr, name='generate_note_qr'),
     path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/<int:student_id>/<int:upload_note_img>/generate_note_qr',\
         views.generate_note_qr, name='generate_note_qr'),
    path('question_nav', views.question_nav, name='question_nav'),
    path('action_menu', views.action_menu, name='action_menu'),
    path('search_question/', views.search_question, name='search_question'),
    path('compare_expressions', views.expression_compare_test, name='compare_expressions'),
    path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/save_note',\
         views.save_note, name='save_note'), 
   path('courses/<int:course_id>/assignments/<int:assignment_id>/questions/<int:question_id>/<int:student_id>/<int:upload_note_img>/save_note',\
         views.save_note, name='save_note'), 
    path('courses/generate_practice_test/<int:practice_course_id>', views.generate_practice_test, name='generate_practice_test'),
    path('courses/practice_test_settings/<int:course_id>/<int:practice_course_id>', views.practice_test_settings, name='practice_test_settings'),
    path('courses/practice_test_settings/<int:course_id>/<int:practice_course_id>/<str:error_message>', views.practice_test_settings, name='practice_test_settings'),    
    path('courses/practice_test_page/<int:course_id>', views.practice_test_page, name='practice_test_page'), 
    path('courses/<int:course_id>/gradebook', views.gradebook, name='gradebook')    
]

deimos/views.py
import json
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .forms import *
from .models import *
from django.shortcuts import get_object_or_404
from django.middleware import csrf
from django.utils.timesince import timesince
from phobos.models import QuestionChoices
import random
import numpy as np
import torch
from sklearn.metrics.pairwise import cosine_similarity
from Dr_R.settings import BERT_TOKENIZER, BERT_MODEL
import heapq
from django.db import transaction
from markdown2 import markdown
from phobos.models import Topic, SubTopic
import qrcode
from phobos.views import export_question_to
from scipy.stats import norm
from .utils import *
from datetime import date

import asyncio
from asgiref.sync import sync_to_async

# Create your views here.
@login_required(login_url='astros:login') 
def index(request):
    student = get_object_or_404(Student, username=request.user.username)
    courses = student.courses.order_by('-timestamp')
    context = {
        "courses": courses
    }
    return render(request, "deimos/index.html", context)

@login_required(login_url='astros:login') 
def course_management(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    # Check if there is any Enrollment entry that matches the given student and course
    student = get_object_or_404(Student, pk = request.user.pk)
    is_enrolled = Enrollment.objects.filter(student=student, course=course).exists()
    if not is_enrolled:
        return HttpResponseForbidden('You are not enrolled in this course.')

    assignments = Assignment.objects.filter(course=course, assignmentstudent__student=student, \
                                            is_assigned=True).order_by('-timestamp')
    as_statuses = []
    if course.name != 'Question Bank':
        for assignment in assignments:
            ass, created = AssignmentStudent.objects.get_or_create(assignment= assignment, student=student)
            as_statuses.append(ass)

    context = {
        "student":student,
        "assignments": zip(assignments, as_statuses),
        "course": course,
    }
    return render(request, "deimos/course_management.html", context)

@login_required(login_url='astros:login') 
def assignment_management(request, assignment_id, course_id=None):
    # Making sure the request is done by a Student.
    student = get_object_or_404(Student, pk = request.user.pk)
    assignment = get_object_or_404(Assignment, pk = assignment_id)
    assignment_student = AssignmentStudent.objects.get(student=student, assignment=assignment)
    questions = Question.objects.filter(assignment = assignment, parent_question=None).order_by('number')
    qs_statuses = []
    if assignment.course.name != 'Question Bank':
        for question in questions:
            qs, created = QuestionStudent.objects.get_or_create(question=question, student=student)
            qs_statuses.append(qs.get_status())
            question.text = qs.evaluate_var_expressions_in_text(question.text, add_html_style=True)
    else:
        qs_statuses = [False for i in range(questions.count())] # here for templating purposes.

    if sum(qs_statuses) == len(qs_statuses): # if all the questions have been completed.
        assignment_student.is_complete = True
    else:
        assignment_student.is_complete = False
    assignment_student.save(update_fields=['is_complete'])
    
    context = {
        "questions": zip(questions, qs_statuses),
        "assignment": assignment,
    }
    return render(request, "deimos/assignment_management.html", context)

@login_required(login_url='astros:login')
def gradebook(request, course_id):
    course = get_object_or_404(Course, pk=course_id)

    # Check if there is any Enrollment entry that matches the given student and course
    student = get_object_or_404(Student, pk = request.user.pk)
    is_enrolled = Enrollment.objects.filter(student=student, course=course).exists()
    if not is_enrolled:
        return HttpResponseForbidden('You are not enrolled in this course.')
    # needed student's gradebook
    course_score = 0
    assignment_student_grade = []
    assignment_students = AssignmentStudent.objects.filter(student=student, assignment__course=course)
    a_sums = 0
    for assignment_s in assignment_students:
        grade = assignment_s.grade
        assignment_student_grade.append({'id':assignment_s.id,'assignment_student':assignment_s,'grade':grade})
        course_score += assignment_s.assignment.grading_scheme.num_points * grade
        a_sums += assignment_s.assignment.grading_scheme.num_points
    if a_sums == 0:
        course_score = 0
    else:
        course_score /= a_sums

    return render(request, 'deimos/gradebook.html', {
        'student': student, 'course':course,
                "assignment_student_grade": assignment_student_grade,
        "course_score": round(course_score, 2),
    })


mcq_related_names = ['mcq_expression_answers', 'mcq_text_answers','mcq_float_answers',
                        'mcq_variable_float_answers','mcq_image_answers','mcq_latex_answers']

# TODO: Add the action link in answer_question.html
# TODO: Implement question_view as well.
@login_required(login_url='astros:login')
def answer_question(request, question_id, assignment_id, course_id, student_id=None, upload_note_img=None):
    # Making sure the request is done by a Student.
    if student_id:
        student = get_object_or_404(Student, pk=student_id)
    else:
        student = get_object_or_404(Student, pk=request.user.pk)
    assignment = get_object_or_404(Assignment, pk=assignment_id)
    if assignment.course.name != 'Question Bank':
        is_questionbank = False
        question_ids = assignment.questions.filter(parent_question=None).values_list('id', flat=True)
        question_nums = assignment.questions.filter(parent_question=None).values_list('number', flat=True)
    else:
        is_questionbank = True
        question_ids, question_nums = [], []
    question_0 = Question.objects.get(pk=question_id)

    if question_0.parent_question: # if the question has a parent question.
        question_0 = question_0.parent_question

    questions = list(question_0.sub_questions.all())
    questions.insert(0, question_0)

    questions_dictionary = {}
    for index, question in enumerate(questions):
        question_student, created = QuestionStudent.objects.get_or_create(question=question, student=student)
        if index==0:
            note, note_created = Note.objects.get_or_create(question_student=question_student)
            note_md = markdown(note.content)
        if created:
            question_student.create_instances()
        else:
            if not question_student.instances_created:
                question_student.create_instances()
        question_student.save() 
        # Detect links and replace with html a-tags
        question.text = replace_links_with_html(question.text)
        labels_urls_list = [(question_image.label, question_image.image.url) for question_image in \
                        question.images.all()]
        question.text = replace_image_labels_with_links(question.text,labels_urls_list)
        # Replace vars with values in colored tags.
        question.text = question_student.evaluate_var_expressions_in_text(question.text, add_html_style=True)
        questtype = ''
        answers = []
        answers_c = None

        if question.answer_type.startswith('MCQ'):
            questtype='mcq'
            # List of answer types that require content evaluation
            answer_types_to_evaluate = ['mcq_expression_answers', 'mcq_variable_float_answers']
            # Loop through each answer type
            for mrn in mcq_related_names:
                # Get the related manager for the answer type
                answer_queryset = getattr(question, mrn).all()
                # If the answer type requires content evaluation, process each answer
                if mrn in answer_types_to_evaluate:
                    for answer in answer_queryset:
                        answer.content = question_student.evaluate_var_expressions_in_text(answer.content, add_html_style=True)
                
                # Extend the answers list with the processed or unprocessed answers
                answers.extend(answer_queryset)
            if not question_student.success: # Do not need to randomize the order if student has already passed.
                random.shuffle(answers)  
        elif question.answer_type.startswith('STRUCT'):
            questtype = 'struct'
            # TODO: Subclass all structural answers to a more general class 
            # so that you may use only one if.
            # Define a mapping from answer_type to the corresponding attribute and question type value
            answer_type_mapping = {
                QuestionChoices.STRUCTURAL_LATEX: 'latex_answer',
                QuestionChoices.STRUCTURAL_EXPRESSION: 'expression_answer',
                QuestionChoices.STRUCTURAL_VARIABLE_FLOAT: 'variable_float_answer',
                QuestionChoices.STRUCTURAL_FLOAT: 'float_answer',
                QuestionChoices.STRUCTURAL_TEXT: 'text_answer',
            }

            # Get the attribute name based on the answer_type
            attribute_name = answer_type_mapping.get(question.answer_type, None)

            # If the attribute name is valid, get the attribute value and extend the lists
            if attribute_name:
                answers.extend([getattr(question, attribute_name)])
            else:

deimos/templates/deimos/assignment_display.html
<!-- deimos: assignment_display.html -->
{% load my_custom_tags %}
<li class="assignment-li course-li" data-assignment-id="{{ assigment.id }}">
    <a href="{% url 'deimos:assignment_management' course_id=course.id assignment_id=assignment.id %}">
        <div class="course-section assigment-section">
            <div>
                <span class="c-name assignment-name"><strong>{{assignment.name | safe}}</strong></span>
                <p class="timestamp" style="display: none;">Created on {{ assignment.timestamp|format_date }}</p>
                {% if assignment.assigned_date %}
                    <p class="timestamp">Assigned on {{ assignment.assigned_date|format_date }}</p>
                {% endif %}
                {% if ass.due_date %}
                    <p class="timestamp">Due on {{ ass.due_date|format_date }}</p>
                {% endif %}
            </div>
            {% if ass.get_status %}
                <button type="button" class="btn status edit-btn" style="position: absolute; bottom: 2%;">
                        Completed
                </button>
            {% endif %}
        </div>
        
    </a>
</li>

deimos/templates/deimos/assignment_gradebook.html
{% extends 'deimos/layout.html' %}
{% block title %} Course {% endblock %}
{% block body%}
<div class="sidebar" style="display:none">
    <header class="sidebar-header">X</header>
    <ul>
        <li><a href="{% url 'deimos:index' %}">Home</a></li>
        <li><a href="{% url 'deimos:search_question' %}">Search Question</a></li>
        <li><a href="{% url 'deimos:course_management' course_id=course_id %}">Back to Course</a></li>
    </ul>
</div>

<nav class="navbar-custom">
        {% for assignment in assignments %}
          <a class="nav-link " href="{% url 'deimos:assignment_gradebook_student' student_id=student.id assignment_id=assignment.id %}">
            {{assignment.assignment.name}} </a>
        {% endfor %}
</nav>



<div>
    <div>
        <style>
            .progress {
              width: 80%;
              height: 20px;
              margin-left:10%;
            }
          </style>
    <br>
    <div class="progress" data-score="{{assignment.grade}}">
        <div class="progress-bar bg-success" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <div class="do-margin">
      <div class="suggestion original-size"> <h5>{{assignment.name}}'s Report</h5> Due on {{assignment.Due_date}} </div>

      <table class="table table-striped table-bordered table-hover">
          <thead>
              <tr>
                  {% for element in question_heading %}
                      <th>{{element}} </th>
                  {% endfor %}
              </tr>
          </thead>
          <tbody>
              {% for question in question_details %}
              <tr>
                  <td>{{question.Question_number}} </td>  
                  <td>{{question.score}} </td> 
                  <td>{{question.num_attempts}} </td> 
              </tr>
              {% endfor %}
          </tbody>
      </table>
    </div>

</div>

<script>
    // Get the progress element
    var progress = document.querySelector(".progress");

    // Set the value of the progress element to the score
     score = ''+progress.dataset.score;

     // Get the progress-bar element inside the progress element
    var progressBar = progress.querySelector(".progress-bar");

    // Add the progress-bar class to the progress-bar element
    progressBar.classList.add("progress-bar");

    // Set the width of the progress-bar element to the score percentage
    progressBar.style.width = score + "%";

    // Set the text inside the progress-bar element to the score percentage
    progressBar.textContent = score + "%";

    // Change the color of the progress-bar element based on the score
    if (score > 94) {
      // If score is greater than 94, use green color
      progressBar.classList.add("bg-success");
    } else if (score > 85) {

      progressBar.classList.add("bg-info");
    } else if (score > 70) {

      progressBar.classList.add("bg-warning");
    } else {

      progressBar.classList.add("bg-danger");
    }
    console.log(progressBar.className)
  </script>
{% endblock %}

deimos/templates/deimos/course_management.html
<!-- deimos: course_management.html-->
{% extends 'deimos/layout.html' %}
{% load my_custom_tags %}
{% load static %}
{% block title %} Course {% endblock %}
{% block body%}
<div class="sidebar" style="display:none">
    <header class="sidebar-header">X</header>
    <ul>
        <li><a href="{% url 'deimos:index' %}">Home</a></li>
        <li><a href="{% url 'astros:course_info' course_id=course.id %}">Course Info</a></li>
        <li><a href="{% url 'deimos:search_question' %}">Search Question</a></li>
        <!--<li><a href="{% url 'deimos:practice_test_settings' course_id=course.id %}">Practice Test</a></li>-->
    </ul>
</div>

<nav class="navbar-custom">
    <a class="nav-link home-btn" href="{% url 'deimos:index' %}">Home </a>
    <a class="nav-link view-notes-btn" href="{% url 'deimos:note_management' course_id=course.id%}">View notes</a>
    <a class="nav-link gradebook-btn" href="{% url 'deimos:gradebook' course_id=course.id%}">GradeBook</a>
</nav>

  <div class="home">
    <div class="sf-container">
        <input type="text" name="search" class="page-search search-field w-limit-50" data-name="assignment-name" placeholder="search assignment" />
    </div>
    <br />
    <h4>{{course.name}}</h4>
    <hr />

    <!-- Display course's assignments -->
    <ul class="courses course-list">
        {% for assignment, ass in assignments %}
            {% include 'deimos/assignment_display.html' with assignment=assignment course=course ass=ass %}
        {% endfor %}
    </ul>
</div>

{% endblock %}
{% block scripts %}
    <script src="{% static 'deimos/js/search_generic.js' %}"></script>
{% endblock %}

deimos/templates/deimos/gradebook.html
{% extends 'deimos/layout.html' %}
{% load static %}
{% block title %} GradeBook {% endblock %}
{% block body %}
<div>
    <style>
            .progress {
              width: 80%;
              height: 20px;
              margin-left:10%;
            }
      </style>

    <div class="sidebar" style="display:none">
      <header class="sidebar-header">X</header>
      <ul>
          <li><a href="{% url 'deimos:index' %}">Home</a></li>
          <a class="nav-link" href="{% url 'deimos:course_management' course_id=course.id%}">Assignments</a>
          <li><a href="{% url 'astros:course_info' course_id=course.id %}">Course Info</a></li>
          <li><a href="{% url 'deimos:search_question' %}">Search Question</a></li>
      </ul>
  </div>
  
  <nav class="navbar-custom">
      <a class="nav-link home-btn" href="{% url 'deimos:index' %}">Home </a>
      <a class="nav-link" href="{% url 'deimos:course_management' course_id=course.id%}">Assignments</a>
      <a class="nav-link view-notes-btn" href="{% url 'deimos:note_management' course_id=course.id%}">View notes</a>
  </nav>
    <div class="progress" data-score="{{course_score}}"><!-- Please calculate total score/100-->
        <div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <div class="sf-container">
      <input type="text" name="search" class="search-field page-search w-limit-50" data-display="table-row"
      data-parent="assignment-row" data-name="assignment-name" placeholder="search by assignment name" />
    </div>
      <div class="do-margin">
        <br>
            <div class="suggestion original-size"><h5>{{student.first_name}} {{student.last_name}}'s Report</h5></div>
        <br>

            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th> Assignments</th>
                        <th> Grades </th>
                    </tr>
                </thead>
                <tbody>
                    {% for assignment in assignment_student_grade %}
                    <tr class="assignment-row">
                        <td> <a href="{% url 'deimos:assignment_gradebook_student' student_id=student.id assignment_id=assignment.id %}">
                            <b class="assignment-name">{{assignment.assignment_student.assignment.name}}</b></a>
                        </td> 
                            <td> {{assignment.grade}} %</td>
                    </tr>
                    {% if forloop.last %}
                      <input  class ="num_assignments" type="hidden" data-num_assignments="{{ forloop.counter}}">
                    {% endif %}
                    {% endfor %}
                    <tr>
                        <td><b>COURSE SCORE</b></td>
                        <td>{{course_score}} %</td>
                    </tr>
                </tbody>
            </table>

      </div>
</div>


<script>
    // Get the progress element
    var progress = document.querySelector(".progress");
    // Set the value of the progress element to the score
    var score = parseFloat(progress.dataset.score)
    score = score.toFixed(2);
     // Get the progress-bar element inside the progress element
    var progressBar = progress.querySelector(".progress-bar");

    // Add the progress-bar class to the progress-bar element
    progressBar.classList.add("progress-bar");

    // Set the width of the progress-bar element to the score percentage
    progressBar.style.width = score + "%";

    // Set the text inside the progress-bar element to the score percentage
    progressBar.textContent = score + "%";

    // Change the color of the progress-bar element based on the score
    if (score > 94) {
      // If score is greater than 94, use green color
      progressBar.classList.add("bg-success");
    } else if (score > 85) {

      progressBar.classList.add("bg-info");
    } else if (score > 70) {

      progressBar.classList.add("bg-warning");
    } else {

      progressBar.classList.add("bg-danger");
    }
    console.log(progressBar.className)
  </script>
{% endblock %}

{% block scripts %}
<script src="{% static 'deimos/js/search_generic.js' %}"></script>
{% endblock %}

deimos/templates/deimos/index.html
<!-- deimos: index.html-->
{% extends 'deimos/layout.html' %}
{% load static %}
{% block body%}

<div class="sidebar" style="display:none">
    <header class="sidebar-header">X</header>
    <ul>
        <li><a href="{% url 'deimos:index' %}">Home</a></li>
        <li><a href="{% url 'astros:all_courses' %}">All courses</a></li>
    </ul>
</div>
<div class="sf-container">
    <input type="text" name="search" class="page-search search-field w-limit-50" data-name="course-name" placeholder="search course" />
</div>
    <h4>My courses</h4> 
   <!-- Display Student's courses -->
    <ul class="courses course-list">
        {% for course in courses%}
            {% include 'deimos/course_display.html' with course=course%}
        {% empty %}
            <h5 class="suggestion original-size" style="width:100%">You are not yet registered for any course.
                Go to <a href="{% url 'astros:all_courses' %}">All courses</a> to see available courses.
            </h5>
        {% endfor %}
    </ul>

{% endblock %}
{% block scripts %}
    <script src="{% static 'deimos/js/search_generic.js' %}"></script>
{% endblock %}

deimos/templates/deimos/practice_test_page.html
<!-- deimos: course_management.html-->
{% extends 'deimos/layout.html' %}
{% load my_custom_tags %}
{% block title %} Course {% endblock %}
{% block style %} <link rel="stylesheet" href=""/> {% endblock %}
{% block body%}
<style>
    .nav-link:hover {
    cursor: pointer;
  }
</style>
<div class="sidebar" style="display:none">
    <header class="sidebar-header">X</header>
    <ul>
        <li><a href="{% url 'deimos:index' %}">Home</a></li>
        <li><a href="{% url 'astros:course_info' course_id=course.id %}">Course Info</a></li>
        <li><a href="{% url 'deimos:search_question' %}">Search Question</a></li>
    </ul>
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light navigation" >
    <div class="container-fluid">
      <ul class="navbar-nav mr-auto" style="list-style: none; display:flex;">
        <li class="nav-item " style="display:inline;">
          <a class="nav-link home-btn" href="{% url 'deimos:course_management' course_id=course.id%}">Home </a>
        </li>
        <li class="nav-item" style="display:inline;">
          <a class="nav-link view-notes-btn" href="{% url 'deimos:note_management' course_id=course.id%}">View notes</a>
        </li>
    </div>
  </nav>

  <div class="home">
    <div id="sf-container">
        <input id="search-field" type="text" name="search" placeholder="search assignment" />
    </div>
    <br />
    <h4>{{course.name}}- PRACTICE TESTS</h4>
    <h4></h4>
    <hr />
    <div class="new_practice_test">
        <div><a href="{% url 'deimos:practice_test_settings' course_id=course.id practice_course_id=practice_course_id %}">
            <button class="btn edit-btn co">New Practice Test</button></div></a>
    </div>
    <!-- Display course's assignments -->
    <ul class="courses course-list">
        {% for assignment in practice_test_assignments %}
        {% include 'deimos/assignment_display.html' with assignment=assignment course=course %}
        {% endfor %}
    </ul>
</div>

<script>

</script>
{% endblock %}

deimos/templates/deimos/practice_test_setting.html
<!-- deimos: assignment_management.html-->
{% extends 'deimos/layout.html' %}
{% block title %} Notes {% endblock %}
{% load static %}
{% block body%}
<div class="sidebar" style="display:none">
    <header class="sidebar-header">X</header>
    <ul>
        <li><a href="{% url 'deimos:index' %}">Home</a></li>
        <li><a href="{% url 'deimos:course_management' course_id=course.id %}">Assignments</a></li>
        <li><a href="{% url 'deimos:search_question' %}">Search Question</a></li>
    </ul>
</div>
    <div class="sf-container">
        <input  class="search-field page-search" type="text" name="search_question" placeholder="search question"/>
    </div>

<nav class="navbar navbar-expand-lg navbar-light bg-light" >
    <div class="container-fluid">
      <ul class="navbar-nav mr-auto" style="list-style: none; display:flex;">
        <li class="nav-item " style="display:inline;">
          <a class="nav-link home-btn" href="{% url 'deimos:course_management' course_id=course.id%}">Home </a>
        </li>
        <li class="nav-item" style="display:inline;">
          <a class="nav-link view-notes-btn" href="{% url 'deimos:note_management' course_id=course.id%}">View notes</a>
        </li>
        <li class="nav-item" style="display:inline;">
            <a class="nav-link grabebook-btn" href="{% url 'deimos:gradebook' course_id=course.id %}">GradeBook</a>
        </li>
        </div>
  </nav>
    <br/>
    <br/>
    <h4 class="suggestion" style="font-size: large;">{{course.name}} - Practice test</h4><hr/>
    
  
  <form action="{% url 'deimos:generate_practice_test' practice_course_id=practice_course_id %}" method="post">
    {% csrf_token %}
    <input type="hidden" value="{{course.id}}" name="course_id"><br>
    <p style="color: red;">{{error_message}} </p>
    - Topic:
<br>
  <select id="selectTopic" name="topic_name" aria-placeholder="Select a Topic">
    {% for topic in topics %}
    <option value="{{topic.name}}">{{topic}} </option>
    {% endfor %}
  </select><br>
<br>
- Subtopic:
<br>
  {% for topic,Subtopics in topicSubtopics %}
  <select data-topic="{{topic.name}}" class = "select_subtopic_class"name="subtopic_{{topic.name}}" aria-placeholder="Select a SubTopic">
    <option value="All"> All</option>
    {% for subtopic in Subtopics %}
    <option value="{{subtopic.name}}">{{subtopic}} </option>
    {% endfor %}
  </select>
  {% endfor %}

  <br>
  - number of Question:
  <br><input name="num_Question" type="number" placeholder="Enter the number of questions" style="width: 70%;">
<br>
- Test title:
<br>
  <input name="practice_test_name" type="text" placeholder="Enter the name of the practice test e.g Practice Mechanics 2" style="width: 70%;"><br><br>
  <input type="submit" value="Generate Practice test">
</form>


{% endblock %}
{% block scripts%}
<script>
  const SelectedSubtopic = document.querySelectorAll(".select_subtopic_class");
  const SelectedTopic = document.querySelector('#selectTopic');

  //initial view
  SelectedSubtopic.forEach(subtopic => {
      subtopic.style.display='none';
    });
  var selectedsubtopic = SelectedSubtopic[0];
  selectedsubtopic.style.display="block";

//display subtopics
  SelectedTopic.addEventListener("change",()=>{
    selectedsubtopic.style.display="none";  // hide previous 
    for(i=0;i<SelectedSubtopic.length;i++){
      if(SelectedSubtopic[i].dataset.topic== SelectedTopic.value){
        selectedsubtopic = SelectedSubtopic[i];
        selectedsubtopic.style.display="block"; // display new
        break;
      }
    }
  })
</script>

<script src="{% static 'deimos/js/search_question.js' %}"></script>
{% endblock %}